// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: wordService.proto

package word

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//-----------------------------------------------------------------
//word Model
//--------------------------------------------------------------------
type Word struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Word string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *Word) Reset() {
	*x = Word{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_wordService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_wordService_proto_rawDescGZIP(), []int{0}
}

func (x *Word) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Word) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

// Add word request
type AddWordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word    *Word  `protobuf:"bytes,1,opt,name=Word,proto3" json:"Word,omitempty"`
	TraceID string `protobuf:"bytes,2,opt,name=TraceID,proto3" json:"TraceID,omitempty"`
}

func (x *AddWordReq) Reset() {
	*x = AddWordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddWordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWordReq) ProtoMessage() {}

func (x *AddWordReq) ProtoReflect() protoreflect.Message {
	mi := &file_wordService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWordReq.ProtoReflect.Descriptor instead.
func (*AddWordReq) Descriptor() ([]byte, []int) {
	return file_wordService_proto_rawDescGZIP(), []int{1}
}

func (x *AddWordReq) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

func (x *AddWordReq) GetTraceID() string {
	if x != nil {
		return x.TraceID
	}
	return ""
}

// Get random word request
type GetRandomWordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceID string `protobuf:"bytes,1,opt,name=TraceID,proto3" json:"TraceID,omitempty"`
}

func (x *GetRandomWordReq) Reset() {
	*x = GetRandomWordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomWordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomWordReq) ProtoMessage() {}

func (x *GetRandomWordReq) ProtoReflect() protoreflect.Message {
	mi := &file_wordService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomWordReq.ProtoReflect.Descriptor instead.
func (*GetRandomWordReq) Descriptor() ([]byte, []int) {
	return file_wordService_proto_rawDescGZIP(), []int{2}
}

func (x *GetRandomWordReq) GetTraceID() string {
	if x != nil {
		return x.TraceID
	}
	return ""
}

// Seach Word Request
type SearchWordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix  string `protobuf:"bytes,1,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	TraceID string `protobuf:"bytes,2,opt,name=TraceID,proto3" json:"TraceID,omitempty"`
}

func (x *SearchWordReq) Reset() {
	*x = SearchWordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchWordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchWordReq) ProtoMessage() {}

func (x *SearchWordReq) ProtoReflect() protoreflect.Message {
	mi := &file_wordService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchWordReq.ProtoReflect.Descriptor instead.
func (*SearchWordReq) Descriptor() ([]byte, []int) {
	return file_wordService_proto_rawDescGZIP(), []int{3}
}

func (x *SearchWordReq) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *SearchWordReq) GetTraceID() string {
	if x != nil {
		return x.TraceID
	}
	return ""
}

// Add new word response.
type WordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word      *Word  `protobuf:"bytes,1,opt,name=Word,proto3" json:"Word,omitempty"`
	TimeStamp uint64 `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *WordRes) Reset() {
	*x = WordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordRes) ProtoMessage() {}

func (x *WordRes) ProtoReflect() protoreflect.Message {
	mi := &file_wordService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordRes.ProtoReflect.Descriptor instead.
func (*WordRes) Descriptor() ([]byte, []int) {
	return file_wordService_proto_rawDescGZIP(), []int{4}
}

func (x *WordRes) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

func (x *WordRes) GetTimeStamp() uint64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

// Search word response
type SearchWordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words     []string `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	TimeStamp uint64   `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *SearchWordRes) Reset() {
	*x = SearchWordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchWordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchWordRes) ProtoMessage() {}

func (x *SearchWordRes) ProtoReflect() protoreflect.Message {
	mi := &file_wordService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchWordRes.ProtoReflect.Descriptor instead.
func (*SearchWordRes) Descriptor() ([]byte, []int) {
	return file_wordService_proto_rawDescGZIP(), []int{5}
}

func (x *SearchWordRes) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *SearchWordRes) GetTimeStamp() uint64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

var File_wordService_proto protoreflect.FileDescriptor

var file_wordService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x77, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2a, 0x0a, 0x04, 0x57, 0x6f, 0x72,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x46, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x57, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x04, 0x57,
	0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x44, 0x22, 0x2c, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x44, 0x22, 0x41, 0x0a, 0x0d, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x44, 0x22, 0x47,
	0x0a, 0x07, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x57, 0x6f, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x57,
	0x6f, 0x72, 0x64, 0x52, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x43, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x32, 0xb2, 0x01, 0x0a,
	0x0b, 0x57, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x2e, 0x77, 0x6f, 0x72,
	0x64, 0x2e, 0x41, 0x64, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x77,
	0x6f, 0x72, 0x64, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x16,
	0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x57,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x57, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x13, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x77, 0x6f, 0x72,
	0x64, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_wordService_proto_rawDescOnce sync.Once
	file_wordService_proto_rawDescData = file_wordService_proto_rawDesc
)

func file_wordService_proto_rawDescGZIP() []byte {
	file_wordService_proto_rawDescOnce.Do(func() {
		file_wordService_proto_rawDescData = protoimpl.X.CompressGZIP(file_wordService_proto_rawDescData)
	})
	return file_wordService_proto_rawDescData
}

var file_wordService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wordService_proto_goTypes = []interface{}{
	(*Word)(nil),             // 0: word.Word
	(*AddWordReq)(nil),       // 1: word.AddWordReq
	(*GetRandomWordReq)(nil), // 2: word.GetRandomWordReq
	(*SearchWordReq)(nil),    // 3: word.SearchWordReq
	(*WordRes)(nil),          // 4: word.WordRes
	(*SearchWordRes)(nil),    // 5: word.SearchWordRes
}
var file_wordService_proto_depIdxs = []int32{
	0, // 0: word.AddWordReq.Word:type_name -> word.Word
	0, // 1: word.WordRes.Word:type_name -> word.Word
	1, // 2: word.WordService.CreateWord:input_type -> word.AddWordReq
	2, // 3: word.WordService.GetRandomWord:input_type -> word.GetRandomWordReq
	3, // 4: word.WordService.SearchWord:input_type -> word.SearchWordReq
	4, // 5: word.WordService.CreateWord:output_type -> word.WordRes
	4, // 6: word.WordService.GetRandomWord:output_type -> word.WordRes
	5, // 7: word.WordService.SearchWord:output_type -> word.SearchWordRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wordService_proto_init() }
func file_wordService_proto_init() {
	if File_wordService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wordService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Word); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddWordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandomWordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchWordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchWordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wordService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wordService_proto_goTypes,
		DependencyIndexes: file_wordService_proto_depIdxs,
		MessageInfos:      file_wordService_proto_msgTypes,
	}.Build()
	File_wordService_proto = out.File
	file_wordService_proto_rawDesc = nil
	file_wordService_proto_goTypes = nil
	file_wordService_proto_depIdxs = nil
}
